# Generated by Django 4.2.17 on 2026-04-13 15:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('reason', models.CharField(choices=[('connect_chat', 'Connect Chat'), ('daily_reward', 'Daily Reward'), ('purchase', 'Purchase'), ('resonate', 'Resonate')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'token_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
