# Generated by Django 4.2.17 on 2026-04-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokentransaction',
            name='reason',
            field=models.CharField(choices=[('connect_chat', 'Connect Chat'), ('daily_reward', 'Daily Reward'), ('purchase', 'Purchase'), ('resonate', 'Resonate'), ('boost', 'Boost')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='tokentransaction',
            index=models.Index(fields=['user', 'created_at'], name='token_user_created_idx'),
        ),
    ]
