# Generated by Django 4.2.17 on 2026-04-13 15:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('echoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('harmony_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('echo1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_echo1', to='echoes.echo')),
                ('echo2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_echo2', to='echoes.echo')),
            ],
            options={
                'db_table': 'matches',
                'ordering': ['-created_at'],
            },
        ),
    ]
