# Generated by Django 4.2.17 on 2026-04-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_is_active'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user1', 'is_active'], name='match_user1_active_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['user2', 'is_active'], name='match_user2_active_idx'),
        ),
    ]
