# Generated by Django 4.2.17 on 2026-04-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echoes', '0003_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daily_prompts',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='echo',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='echo',
            name='mood',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
