# Generated by Django 4.2.17 on 2026-04-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echoes', '0004_dailyprompt_echo_expires_at_echo_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='echo',
            name='boost_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='echo',
            name='is_boosted',
            field=models.BooleanField(default=False),
        ),
    ]
