# Generated by Django 4.2.17 on 2026-04-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echoes', '0005_echo_is_boosted_echo_boost_count'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='echo',
            index=models.Index(fields=['author', 'expires_at'], name='echo_author_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='echo',
            index=models.Index(fields=['expires_at'], name='echo_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='echo',
            index=models.Index(fields=['mood'], name='echo_mood_idx'),
        ),
    ]
