# Generated by Django 4.2.17 on 2026-04-22 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('echoes', '0006_echo_echo_author_expires_idx_echo_echo_expires_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResonanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('echo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resonance_records', to='echoes.echo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resonance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resonance_records',
            },
        ),
        migrations.AddConstraint(
            model_name='resonancerecord',
            constraint=models.UniqueConstraint(fields=('user', 'echo'), name='unique_user_echo_resonance'),
        ),
    ]
