# Generated by Django 4.2.17 on 2026-04-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echoes', '0007_resonancerecord_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='echo',
            index=models.Index(fields=['is_boosted', 'created_at'], name='echo_boost_feed_idx'),
        ),
    ]
