# Generated by Django 4.2.17 on 2026-04-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['match', 'created_at'], name='message_match_created_idx'),
        ),
    ]
